### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by gabelluardo** [policumbent/policumbent-website#3]
### Chrome:
![immagine](https://user-images.githubusercontent.com/42920247/111881766-5e0c9900-89b2-11eb-862a-0e55cc75abc5.png)
### Firefox:
![immagine](https://user-images.githubusercontent.com/42920247/111881786-77ade080-89b2-11eb-9110-42fbfe1806bd.png)

## Solution

```scss
$background-color: white;
$main-color: gray;

/* Works on Firefox */
* {
  scrollbar-width: thin;
  scrollbar-color: $main-color $background-color;
}

/* Works on Chrome, Edge, and Safari */
*::-webkit-scrollbar {
  width: 10px;
}

*::-webkit-scrollbar-track {
  background: $background-color;
}

*::-webkit-scrollbar-thumb {
  background-color: $main-color;
  border-radius: 20px;
  border: 3px solid $background-color;
}
```

We can also remove `$background-color` for having a floating scrollbar. These colors are just placeholders.
